services:
  - type: web
    name: fraud-api
    env: python
    buildCommand: "pip install -r requirements.txt && python create_sample_data.py && python train_models_for_api.py"
    startCommand: "gunicorn serve_model:app"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.19

  - type: web
    name: fraud-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt && python create_sample_data.py"
    startCommand: "gunicorn dashboard_app:server"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.19
      - key: API_BASE_URL
        fromService:
          type: web
          name: fraud-api
          property: url
